# Left için: kelime|L
# Right için: kelime|R
# İkisi için: kelime|B
PREDEFINED = [
    "Adın ne?|B",
    "Adın nedir?|B",
    "Adın neydi?|B",
    "Adınız ne?|B",
    "Adınız nedir?|B",
    "Adınız neydi?|B",
    "Afedersin.|B",
    "Afedersiniz.|B",
    "Afiyet olsun.|B",
    "Ancak|L",
    "Anlamadım.|R",
    "Anlamıyorum.|R",
    "Anlayamadım.|R",
    "Ben çok iyiyim.|B",
    "Ben de çok iyiyim.|B",
    "Ben de iyiyim.|B",
    "Ben de memnun oldum.|B",
    "Bence de|L",
    "Bilmiyorum.|B",
    "Bugün hava çok güzel.|B",
    "Bugün hava güneşli.|B",
    "Bugün hava yağmurlu.|B",
    "Bugün neler yaptın?|B",
    "Bunları duyduğuma memnun oldum.|B",
    "Bunları duyduğuma sevindim.|B",
    "Bunu duyduğuma memnun oldum.|B",
    "Bunu duyduğuma sevindim.|B",
    "Çok iyiyim.|B",
    "Çok teşekkür ederim.|B",
    "Çok teşekkürler.|B",
    "Eline sağlık.|B",
    "Elinize sağlık.|B",
    "Ellerine sağlık.|B",
    "Ellerinize sağlık.|B",
    "Eyvallah.|B",
    "Fakat|L",
    "Geçmiş olsun.|B",
    "Görüşmek üzere.|B",
    "Görüşürüz.|B",
    "Güle güle.|B",
    "Günaydın.|B",
    "Günün nasıldı?|B",
    "Hayat nasıl?|B",
    "Hiçbir fikrim yok.|B",
    "Hoş geldin.|B",
    "Hoş geldiniz.|B",
    "Hoşbulduk.|B",
    "Hoşçakal.|B",
    "Hoşgeldin.|B",
    "Hoşgeldiniz.|B",
    "İsim ne?|R",
    "İsim neydi?|R",
    "İsmin ne?|R",
    "İsmin neydi?|R",
    "İsminiz ne?|R",
    "İsminiz neydi?|R",
    "İyi akşamlar.|B",
    "İyi değilim.|B",
    "İyi geceler.|B",
    "İyi günler.|B",
    "İyi olmuş.|B",
    "İyiyim.|B",
    "Kendine iyi bak.|B",
    "Kolay gelsin.|B",
    "Kötüyüm.|B",
    "Lakin|L",
    "Memnun oldum.|B",
    "Merhaba.|B",
    "mi?|R",
    "midir?|R",
    "misin?|R",
    "misiniz?|R",
    "mı?|R",
    "mıdır?|R",
    "mısın?|R",
    "mısınız?|R",
    "mu?|R",
    "mü?|R",
    "mudur?|R",
    "müdür?|R",
    "musun?|R",
    "müsün?|R",
    "musunuz?|R",
    "müsünüz?|R",
    "Nasıl yardımcı olabilirim?|B",
    "Nasılsın?|R",
    "Nasılsınız?|R",
    "Neredesin?|R",
    "Nerelisin?|R",
    "Özür dilerim.|B",
    "Pekala.|B",
    "Peki.|B",
    "Rica ederim.|B",
    "Saat kaç?|R",
    "Sağol.|B",
    "Sağolun.|B",
    "Sana da kolay gelsin.|B",
    "Selam.|B",
    "Selamlar.|B",
    "Sen de hoş geldin.|B",
    "Sen de hoşgeldin.|B",
    "Sen nerelisin?|B",
    "Senin adın ne?|B",
    "Senin adın nedir?|B",
    "Senin adın neydi?|B",
    "Senin isim ne?|B",
    "Senin isim neydi?|B",
    "Senin ismin ne?|B",
    "Senin ismin neydi?|B",
    "Siz de hoş geldiniz.|B",
    "Siz de hoş geldiniz.|B",
    "Siz nasılsınız?|B",
    "Size de kolay gelsin.|B",
    "Size nasıl yardımcı olabilirim?|B",
    "Sizin adınız ne?|B",
    "Sizin adınız nedir?|B",
    "Sizin adınız neydi?|B",
    "Sizin isminiz ne?|B",
    "Sizin isminiz neydi?|B",
    "Sizlere de kolay gelsin.|B",
    "Sonra görüşürüz.|B",
    "Tamam da|L",
    "Tamam.|B",
    "Tanıştığıma memnun oldum.|B",
    "Teşekkür ederim.|B",
    "Teşekkürler.|B",
]